repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.8
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: django-system-check
        name: Django system check
        entry: bash -c 'uv run manage.py check --fail-level=ERROR'
        language: system
        types: [python]
      - id: django-migrations-check
        name: Django missing migrations check
        entry: bash -c 'uv run manage.py makemigrations --check --dry-run'
        language: system
        types: [python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs
          - django-stubs-ext
          - python-dotenv

  - repo: local
    hooks:
      - id: tests_sh
        name: Run test.sh
        entry: bash -c './test.sh'
        language: system
        pass_filenames: false
        always_run: true
