line-length = 80
indent-width = 4

exclude = [
    ".git",
    ".venv",
    "coverage/",
    "**/migrations/**",
    "static/",
    "templates/",
]

[lint]
select = [
    "E",
    "F",
    "B",
    "DJ",
    "I",
    "N",
    "UP",
    "SIM",
    "T20",
    "S",
    "ANN",
    "D",
    "TD",
    "C4",
]
ignore = ["D203", "D212", "S311"]
fixable = ["ALL"]
unfixable = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
docstring-code-format = true
docstring-code-line-length = "dynamic"
