# Generated by Django 5.2.5 on 2025-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shusshin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country_code", "JP"), _negated=True),
                fields=("country_code",),
                name="unique_shusshin_country_except_japan",
            ),
        ),
        migrations.AddConstraint(
            model_name="shusshin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country_code", "JP")),
                fields=("jp_prefecture",),
                name="unique_shusshin_jp_prefecture",
            ),
        ),
    ]
