"""Enumeration of Japanese prefecture codes."""

from django.db.models import TextChoices


class JPPrefecture(TextChoices):
    """ISO 3166-2 codes for Japanese prefectures."""

    HOKKAIDO = "JP-01", "Hokkaido"
    AOMORI = "JP-02", "Aomori"
    IWATE = "JP-03", "Iwate"
    MIYAGI = "JP-04", "Miyagi"
    AKITA = "JP-05", "Akita"
    YAMAGATA = "JP-06", "Yamagata"
    FUKUSHIMA = "JP-07", "Fukushima"
    IBARAKI = "JP-08", "Ibaraki"
    TOCHIGI = "JP-09", "Tochigi"
    GUNMA = "JP-10", "Gunma"
    SAITAMA = "JP-11", "Saitama"
    CHIBA = "JP-12", "Chiba"
    TOKYO = "JP-13", "Tokyo"
    KANAGAWA = "JP-14", "Kanagawa"
    NIIGATA = "JP-15", "Niigata"
    TOYAMA = "JP-16", "Toyama"
    ISHIKAWA = "JP-17", "Ishikawa"
    FUKUI = "JP-18", "Fukui"
    YAMANASHI = "JP-19", "Yamanashi"
    NAGANO = "JP-20", "Nagano"
    GIFU = "JP-21", "Gifu"
    SHIZUOKA = "JP-22", "Shizuoka"
    AICHI = "JP-23", "Aichi"
    MIE = "JP-24", "Mie"
    SHIGA = "JP-25", "Shiga"
    KYOTO = "JP-26", "Kyoto"
    OSAKA = "JP-27", "Osaka"
    HYOGO = "JP-28", "Hyogo"
    NARA = "JP-29", "Nara"
    WAKAYAMA = "JP-30", "Wakayama"
    TOTTORI = "JP-31", "Tottori"
    SHIMANE = "JP-32", "Shimane"
    OKAYAMA = "JP-33", "Okayama"
    HIROSHIMA = "JP-34", "Hiroshima"
    YAMAGUCHI = "JP-35", "Yamaguchi"
    TOKUSHIMA = "JP-36", "Tokushima"
    KAGAWA = "JP-37", "Kagawa"
    EHIME = "JP-38", "Ehime"
    KOCHI = "JP-39", "Kochi"
    FUKUOKA = "JP-40", "Fukuoka"
    SAGA = "JP-41", "Saga"
    NAGASAKI = "JP-42", "Nagasaki"
    KUMAMOTO = "JP-43", "Kumamoto"
    OITA = "JP-44", "Oita"
    MIYAZAKI = "JP-45", "Miyazaki"
    KAGOSHIMA = "JP-46", "Kagoshima"
    OKINAWA = "JP-47", "Okinawa"
