# Generated by Django 5.2.10 on 2026-01-26 15:17

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('level', models.PositiveSmallIntegerField(help_text='Division level (1=Makuuchi/highest, 8=Banzuke-gai/lowest)', primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('M', 'Makuuchi'), ('J', 'Juryo'), ('Ms', 'Makushita'), ('Sd', 'Sandanme'), ('Jd', 'Jonidan'), ('Jk', 'Jonokuchi'), ('Mz', 'Mae-zumo'), ('Bg', 'Banzuke-gai')], help_text='Division short code (e.g., M=Makuuchi, J=Juryo)', max_length=2)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'ordering': ['level'],
                'constraints': [models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 8)), name='division_level_valid_range', violation_error_message='Division level must be between 1 and 8.'), models.UniqueConstraint(fields=('name',), name='unique_division_name')],
            },
        ),
        migrations.CreateModel(
            name='GameDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Game Date',
                'verbose_name_plural': 'Game Dates',
                'ordering': ['-year', '-month', '-day'],
                'indexes': [models.Index(fields=['-year', '-month', '-day'], name='gamedate_current_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='gamedate_month_valid_range', violation_error_message='Month must be between 1 and 12.'), models.CheckConstraint(condition=models.Q(('day__gte', 1), ('day__lte', 24)), name='gamedate_day_valid_range', violation_error_message='Day must be between 1 and 24.'), models.UniqueConstraint(fields=('year', 'month', 'day'), name='unique_game_date', violation_error_message='This game date already exists.')],
            },
        ),
        migrations.CreateModel(
            name='Banzuke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tournament (e.g., Hatsu Basho)', max_length=64)),
                ('location', models.CharField(help_text='Location of the tournament (e.g., Tokyo, Osaka)', max_length=64)),
                ('year', models.PositiveIntegerField(help_text='Year of the tournament')),
                ('month', models.PositiveIntegerField(help_text='Month of the tournament')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='SCHEDULED', help_text='Current status of the tournament', max_length=20)),
                ('end_date', models.ForeignKey(help_text='Last day of the tournament (Senshuraku)', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_ends', to='game.gamedate')),
                ('start_date', models.ForeignKey(help_text='First day of the tournament', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_starts', to='game.gamedate')),
            ],
            options={
                'verbose_name': 'Banzuke',
                'verbose_name_plural': 'Banzuke',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Heya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_player_controlled', models.BooleanField(default=False, help_text='Whether this stable is controlled by a player')),
                ('created_at', models.ForeignKey(help_text='Date the stable was founded', on_delete=django.db.models.deletion.PROTECT, related_name='heya_created_at', to='game.gamedate', verbose_name='Founded Date')),
                ('owner', models.OneToOneField(blank=True, help_text='Player who owns this stable (null for AI-controlled)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heya', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Heya',
                'verbose_name_plural': 'Heya',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Y', 'Yokozuna'), ('O', 'Ozeki'), ('S', 'Sekiwake'), ('K', 'Komusubi'), ('M', 'Maegashira'), ('J', 'Juryo'), ('Ms', 'Makushita'), ('Sd', 'Sandanme'), ('Jd', 'Jonidan'), ('Jk', 'Jonokuchi'), ('Mz', 'Mae-zumo'), ('Bg', 'Banzuke-gai')], help_text='Rank title short code (e.g., Y=Yokozuna, O=Ozeki)', max_length=2)),
                ('level', models.PositiveSmallIntegerField(help_text='Hierarchical level (1=highest/Yokozuna, 12=lowest/Banzuke-gai)')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Positional number within rank (e.g., Maegashira 1, 2, 3...)')),
                ('direction', models.CharField(blank=True, choices=[('E', 'East'), ('W', 'West')], default='', help_text='Side of banzuke (E=East, W=West)', max_length=1)),
                ('division', models.ForeignKey(help_text='Division this rank belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='ranks', to='game.division')),
            ],
            options={
                'verbose_name': 'Rank',
                'verbose_name_plural': 'Ranks',
                'ordering': ['level', 'order', 'direction'],
            },
        ),
        migrations.CreateModel(
            name='Rikishi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential', models.PositiveIntegerField(help_text='Maximum total stat points this wrestler can achieve')),
                ('xp', models.PositiveIntegerField(default=0, help_text='Experience points earned through training and competition')),
                ('strength', models.PositiveIntegerField(default=1, help_text='Physical power and pushing ability')),
                ('technique', models.PositiveIntegerField(default=1, help_text='Technical skill and knowledge of techniques')),
                ('balance', models.PositiveIntegerField(default=1, help_text='Stability and ability to maintain footing')),
                ('endurance', models.PositiveIntegerField(default=1, help_text='Stamina and ability to sustain effort')),
                ('mental', models.PositiveIntegerField(default=1, help_text='Mental fortitude and fighting spirit')),
                ('debut', models.ForeignKey(blank=True, help_text='Date of first professional match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debut_rikishi', to='game.gamedate', verbose_name='Debut date')),
                ('heya', models.ForeignKey(blank=True, help_text='Stable the wrestler belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rikishi', to='game.heya', verbose_name='Heya')),
                ('intai', models.ForeignKey(blank=True, help_text='Date of retirement from professional sumo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retired_rikishi', to='game.gamedate', verbose_name='Retirement date')),
                ('rank', models.ForeignKey(blank=True, help_text='Current rank in the banzuke (ranking system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rikishi', to='game.rank', verbose_name='Rank')),
            ],
            options={
                'verbose_name': 'Rikishi',
                'verbose_name_plural': 'Rikishi',
                'ordering': ['shikona__transliteration'],
            },
        ),
        migrations.CreateModel(
            name='BanzukeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveSmallIntegerField(default=0, help_text='Number of wins')),
                ('losses', models.PositiveSmallIntegerField(default=0, help_text='Number of losses')),
                ('absences', models.PositiveSmallIntegerField(default=0, help_text='Number of absences (fusenpai/kyujo)')),
                ('banzuke', models.ForeignKey(help_text='Tournament this entry belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='game.banzuke')),
                ('rank', models.ForeignKey(help_text='Rank held during this tournament', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_entries', to='game.rank')),
                ('rikishi', models.ForeignKey(help_text='Wrestler', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_entries', to='game.rikishi')),
            ],
            options={
                'verbose_name': 'Banzuke Entry',
                'verbose_name_plural': 'Banzuke Entries',
                'ordering': ['banzuke', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Shikona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('transliteration', models.CharField(max_length=32, unique=True)),
                ('interpretation', models.CharField(max_length=64)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional parent shikona representing name lineage or evolution. In sumo tradition, wrestlers may adopt names honoring previous legendary wrestlers, or when a wrestler retires and becomes an oyakata (stable master), their former ring name may be inherited by a successor. This field tracks such historical relationships.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='game.shikona')),
            ],
            options={
                'verbose_name': 'Shikona',
                'verbose_name_plural': 'Shikona',
                'ordering': ['transliteration'],
            },
        ),
        migrations.AddField(
            model_name='rikishi',
            name='shikona',
            field=models.ForeignKey(help_text='Ring name of the wrestler', on_delete=django.db.models.deletion.PROTECT, related_name='rikishi', to='game.shikona', verbose_name='Shikona'),
        ),
        migrations.AddField(
            model_name='heya',
            name='name',
            field=models.ForeignKey(help_text="Name of the stable (e.g., 'Miyagino')", on_delete=django.db.models.deletion.PROTECT, related_name='heya_name', to='game.shikona', verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='Shusshin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(choices=[('AW', 'Aruba'), ('AF', 'Afghanistan'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AX', 'Åland Islands'), ('AL', 'Albania'), ('AD', 'Andorra'), ('AE', 'United Arab Emirates'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AS', 'American Samoa'), ('AQ', 'Antarctica'), ('TF', 'French Southern Territories'), ('AG', 'Antigua and Barbuda'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaijan'), ('BI', 'Burundi'), ('BE', 'Belgium'), ('BJ', 'Benin'), ('BQ', 'Bonaire, Sint Eustatius and Saba'), ('BF', 'Burkina Faso'), ('BD', 'Bangladesh'), ('BG', 'Bulgaria'), ('BH', 'Bahrain'), ('BS', 'Bahamas'), ('BA', 'Bosnia and Herzegovina'), ('BL', 'Saint Barthélemy'), ('BY', 'Belarus'), ('BZ', 'Belize'), ('BM', 'Bermuda'), ('BO', 'Bolivia'), ('BR', 'Brazil'), ('BB', 'Barbados'), ('BN', 'Brunei Darussalam'), ('BT', 'Bhutan'), ('BV', 'Bouvet Island'), ('BW', 'Botswana'), ('CF', 'Central African Republic'), ('CA', 'Canada'), ('CC', 'Cocos (Keeling) Islands'), ('CH', 'Switzerland'), ('CL', 'Chile'), ('CN', 'China'), ('CI', "Côte d'Ivoire"), ('CM', 'Cameroon'), ('CD', 'Democratic Republic of the Congo'), ('CG', 'Congo'), ('CK', 'Cook Islands'), ('CO', 'Colombia'), ('KM', 'Comoros'), ('CV', 'Cabo Verde'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CX', 'Christmas Island'), ('KY', 'Cayman Islands'), ('CY', 'Cyprus'), ('CZ', 'Czechia'), ('DE', 'Germany'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DK', 'Denmark'), ('DO', 'Dominican Republic'), ('DZ', 'Algeria'), ('EC', 'Ecuador'), ('EG', 'Egypt'), ('ER', 'Eritrea'), ('EH', 'Western Sahara'), ('ES', 'Spain'), ('EE', 'Estonia'), ('ET', 'Ethiopia'), ('FI', 'Finland'), ('FJ', 'Fiji'), ('FK', 'Falkland Islands (Malvinas)'), ('FR', 'France'), ('FO', 'Faroe Islands'), ('FM', 'Micronesia'), ('GA', 'Gabon'), ('GB', 'United Kingdom'), ('GE', 'Georgia'), ('GG', 'Guernsey'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GN', 'Guinea'), ('GP', 'Guadeloupe'), ('GM', 'Gambia'), ('GW', 'Guinea-Bissau'), ('GQ', 'Equatorial Guinea'), ('GR', 'Greece'), ('GD', 'Grenada'), ('GL', 'Greenland'), ('GT', 'Guatemala'), ('GF', 'French Guiana'), ('GU', 'Guam'), ('GY', 'Guyana'), ('HK', 'Hong Kong'), ('HM', 'Heard Island and McDonald Islands'), ('HN', 'Honduras'), ('HR', 'Croatia'), ('HT', 'Haiti'), ('HU', 'Hungary'), ('ID', 'Indonesia'), ('IM', 'Isle of Man'), ('IN', 'India'), ('IO', 'British Indian Ocean Territory'), ('IE', 'Ireland'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('IS', 'Iceland'), ('IL', 'Israel'), ('IT', 'Italy'), ('JM', 'Jamaica'), ('JE', 'Jersey'), ('JO', 'Jordan'), ('JP', 'Japan'), ('KZ', 'Kazakhstan'), ('KE', 'Kenya'), ('KG', 'Kyrgyzstan'), ('KH', 'Cambodia'), ('KI', 'Kiribati'), ('KN', 'Saint Kitts and Nevis'), ('KR', 'South Korea'), ('KW', 'Kuwait'), ('LA', 'Laos'), ('LB', 'Lebanon'), ('LR', 'Liberia'), ('LY', 'Libya'), ('LC', 'Saint Lucia'), ('LI', 'Liechtenstein'), ('LK', 'Sri Lanka'), ('LS', 'Lesotho'), ('LT', 'Lithuania'), ('LU', 'Luxembourg'), ('LV', 'Latvia'), ('MO', 'Macao'), ('MF', 'Saint Martin'), ('MA', 'Morocco'), ('MC', 'Monaco'), ('MD', 'Moldova'), ('MG', 'Madagascar'), ('MV', 'Maldives'), ('MX', 'Mexico'), ('MH', 'Marshall Islands'), ('MK', 'North Macedonia'), ('ML', 'Mali'), ('MT', 'Malta'), ('MM', 'Myanmar'), ('ME', 'Montenegro'), ('MN', 'Mongolia'), ('MP', 'Northern Mariana Islands'), ('MZ', 'Mozambique'), ('MR', 'Mauritania'), ('MS', 'Montserrat'), ('MQ', 'Martinique'), ('MU', 'Mauritius'), ('MW', 'Malawi'), ('MY', 'Malaysia'), ('YT', 'Mayotte'), ('NA', 'Namibia'), ('NC', 'New Caledonia'), ('NE', 'Niger'), ('NF', 'Norfolk Island'), ('NG', 'Nigeria'), ('NI', 'Nicaragua'), ('NU', 'Niue'), ('NL', 'Netherlands'), ('NO', 'Norway'), ('NP', 'Nepal'), ('NR', 'Nauru'), ('NZ', 'New Zealand'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PA', 'Panama'), ('PN', 'Pitcairn'), ('PE', 'Peru'), ('PH', 'Philippines'), ('PW', 'Palau'), ('PG', 'Papua New Guinea'), ('PL', 'Poland'), ('PR', 'Puerto Rico'), ('KP', 'North Korea'), ('PT', 'Portugal'), ('PY', 'Paraguay'), ('PS', 'Palestine'), ('PF', 'French Polynesia'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Romania'), ('RU', 'Russia'), ('RW', 'Rwanda'), ('SA', 'Saudi Arabia'), ('SD', 'Sudan'), ('SN', 'Senegal'), ('SG', 'Singapore'), ('GS', 'South Georgia and the South Sandwich Islands'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('SJ', 'Svalbard and Jan Mayen'), ('SB', 'Solomon Islands'), ('SL', 'Sierra Leone'), ('SV', 'El Salvador'), ('SM', 'San Marino'), ('SO', 'Somalia'), ('PM', 'Saint Pierre and Miquelon'), ('RS', 'Serbia'), ('SS', 'South Sudan'), ('ST', 'Sao Tome and Principe'), ('SR', 'Suriname'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('SE', 'Sweden'), ('SZ', 'Eswatini'), ('SX', 'Sint Maarten'), ('SC', 'Seychelles'), ('SY', 'Syria'), ('TC', 'Turks and Caicos Islands'), ('TD', 'Chad'), ('TG', 'Togo'), ('TH', 'Thailand'), ('TJ', 'Tajikistan'), ('TK', 'Tokelau'), ('TM', 'Turkmenistan'), ('TL', 'Timor-Leste'), ('TO', 'Tonga'), ('TT', 'Trinidad and Tobago'), ('TN', 'Tunisia'), ('TR', 'Turkey'), ('TV', 'Tuvalu'), ('TW', 'Taiwan'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('UA', 'Ukraine'), ('UM', 'United States Minor Outlying Islands'), ('UY', 'Uruguay'), ('US', 'United States'), ('UZ', 'Uzbekistan'), ('VA', 'Holy See (Vatican City State)'), ('VC', 'Saint Vincent and the Grenadines'), ('VE', 'Venezuela'), ('VG', 'British Virgin Islands'), ('VI', 'U.S. Virgin Islands'), ('VN', 'Viet Nam'), ('VU', 'Vanuatu'), ('WF', 'Wallis and Futuna'), ('WS', 'Samoa'), ('YE', 'Yemen'), ('ZA', 'South Africa'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2)),
                ('jp_prefecture', models.CharField(blank=True, choices=[('JP-01', 'Hokkaido'), ('JP-02', 'Aomori'), ('JP-03', 'Iwate'), ('JP-04', 'Miyagi'), ('JP-05', 'Akita'), ('JP-06', 'Yamagata'), ('JP-07', 'Fukushima'), ('JP-08', 'Ibaraki'), ('JP-09', 'Tochigi'), ('JP-10', 'Gunma'), ('JP-11', 'Saitama'), ('JP-12', 'Chiba'), ('JP-13', 'Tokyo'), ('JP-14', 'Kanagawa'), ('JP-15', 'Niigata'), ('JP-16', 'Toyama'), ('JP-17', 'Ishikawa'), ('JP-18', 'Fukui'), ('JP-19', 'Yamanashi'), ('JP-20', 'Nagano'), ('JP-21', 'Gifu'), ('JP-22', 'Shizuoka'), ('JP-23', 'Aichi'), ('JP-24', 'Mie'), ('JP-25', 'Shiga'), ('JP-26', 'Kyoto'), ('JP-27', 'Osaka'), ('JP-28', 'Hyogo'), ('JP-29', 'Nara'), ('JP-30', 'Wakayama'), ('JP-31', 'Tottori'), ('JP-32', 'Shimane'), ('JP-33', 'Okayama'), ('JP-34', 'Hiroshima'), ('JP-35', 'Yamaguchi'), ('JP-36', 'Tokushima'), ('JP-37', 'Kagawa'), ('JP-38', 'Ehime'), ('JP-39', 'Kochi'), ('JP-40', 'Fukuoka'), ('JP-41', 'Saga'), ('JP-42', 'Nagasaki'), ('JP-43', 'Kumamoto'), ('JP-44', 'Oita'), ('JP-45', 'Miyazaki'), ('JP-46', 'Kagoshima'), ('JP-47', 'Okinawa')], default='', max_length=5)),
            ],
            options={
                'verbose_name': 'Shusshin',
                'verbose_name_plural': 'Shusshin',
                'ordering': ['country_code', 'jp_prefecture'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('country_code', 'JP'), models.Q(('jp_prefecture', ''), _negated=True)), models.Q(models.Q(('country_code', 'JP'), _negated=True), ('jp_prefecture', '')), _connector='OR'), name='jp_prefecture_required_only_for_jp'), models.UniqueConstraint(condition=models.Q(('country_code', 'JP'), _negated=True), fields=('country_code',), name='unique_shusshin_country_except_japan'), models.UniqueConstraint(condition=models.Q(('country_code', 'JP')), fields=('jp_prefecture',), name='unique_shusshin_jp_prefecture')],
            },
        ),
        migrations.AddField(
            model_name='rikishi',
            name='shusshin',
            field=models.ForeignKey(blank=True, help_text='Place of origin for the wrestler', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rikishi', to='game.shusshin', verbose_name='Shusshin'),
        ),
        migrations.AddConstraint(
            model_name='banzuke',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_banzuke_season'),
        ),
        migrations.AddConstraint(
            model_name='banzuke',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='banzuke_valid_month', violation_error_message='Month must be between 1 and 12.'),
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 12)), name='rank_level_valid_range', violation_error_message='Rank level must be between 1 and 12.'),
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='rank_order_non_negative', violation_error_message='Rank order must be non-negative.'),
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', ''), ('order', 0)), models.Q(('order__gt', 0), models.Q(('direction', ''), _negated=True)), _connector='OR'), name='rank_direction_required_with_order', violation_error_message='Direction required when order is greater than 0.'),
        ),
        migrations.AddConstraint(
            model_name='rank',
            constraint=models.UniqueConstraint(fields=('division', 'title', 'order', 'direction'), name='unique_rank_position'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.UniqueConstraint(fields=('banzuke', 'rikishi'), name='unique_rikishi_per_banzuke', violation_error_message='Rikishi can only appear once in a Banzuke.'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.UniqueConstraint(fields=('banzuke', 'rank'), name='unique_rank_per_banzuke', violation_error_message='Rank can only be held by one Rikishi per Banzuke.'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.CheckConstraint(condition=models.Q(('wins__lte', 15), ('losses__lte', 15), ('absences__lte', 15)), name='banzukeentry_valid_match_counts', violation_error_message='Wins, losses, and absences cannot exceed 15.'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.CheckConstraint(condition=models.Q(('wins__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(15), '-', models.F('losses')), '-', models.F('absences')))), name='banzukeentry_total_matches_max_15', violation_error_message='Total matches cannot exceed 15.'),
        ),
        migrations.AddConstraint(
            model_name='shikona',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('id')), _negated=True), _connector='OR'), name='shikona_parent_not_self', violation_error_message='A shikona cannot be its own parent.'),
        ),
        migrations.AlterUniqueTogether(
            name='shikona',
            unique_together={('name', 'transliteration')},
        ),
        migrations.AddIndex(
            model_name='rikishi',
            index=models.Index(fields=['shikona'], name='rikishi_shikona_idx'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('strength__gte', 1)), name='rikishi_strength_min', violation_error_message='Strength must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('strength__lte', 20)), name='rikishi_strength_max', violation_error_message='Strength cannot exceed 20.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('technique__gte', 1)), name='rikishi_technique_min', violation_error_message='Technique must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('technique__lte', 20)), name='rikishi_technique_max', violation_error_message='Technique cannot exceed 20.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 1)), name='rikishi_balance_min', violation_error_message='Balance must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('balance__lte', 20)), name='rikishi_balance_max', violation_error_message='Balance cannot exceed 20.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('endurance__gte', 1)), name='rikishi_endurance_min', violation_error_message='Endurance must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('endurance__lte', 20)), name='rikishi_endurance_max', violation_error_message='Endurance cannot exceed 20.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('mental__gte', 1)), name='rikishi_mental_min', violation_error_message='Mental must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('mental__lte', 20)), name='rikishi_mental_max', violation_error_message='Mental cannot exceed 20.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('potential__gte', 5), ('potential__lte', 100)), name='rikishi_potential_range', violation_error_message='Potential must be between 5 and 100.'),
        ),
        migrations.AddConstraint(
            model_name='rikishi',
            constraint=models.CheckConstraint(condition=models.Q(('potential__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('strength'), '+', models.F('technique')), '+', models.F('balance')), '+', models.F('endurance')), '+', models.F('mental')))), name='rikishi_current_within_potential', violation_error_message='Total stats cannot exceed potential.'),
        ),
    ]
