# Generated by Django 5.2.5 on 2025-08-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_populate_shusshin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shikona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
                ('transliteration', models.CharField(max_length=32, unique=True)),
                ('interpretation', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Shikona',
                'verbose_name_plural': 'Shikona',
                'ordering': ['transliteration'],
                'unique_together': {('name', 'transliteration')},
            },
        ),
    ]
