# Generated by Django 5.2.5 on 2025-11-28 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_populate_divisions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banzuke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the tournament (e.g., Hatsu Basho)', max_length=64)),
                ('location', models.CharField(help_text='Location of the tournament (e.g., Tokyo, Osaka)', max_length=64)),
                ('year', models.PositiveIntegerField(help_text='Year of the tournament')),
                ('month', models.PositiveIntegerField(help_text='Month of the tournament')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='SCHEDULED', help_text='Current status of the tournament', max_length=20)),
                ('end_date', models.ForeignKey(help_text='Last day of the tournament (Senshuraku)', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_ends', to='game.gamedate')),
                ('start_date', models.ForeignKey(help_text='First day of the tournament', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_starts', to='game.gamedate')),
            ],
            options={
                'verbose_name': 'Banzuke',
                'verbose_name_plural': 'Banzuke',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='BanzukeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveSmallIntegerField(default=0, help_text='Number of wins')),
                ('losses', models.PositiveSmallIntegerField(default=0, help_text='Number of losses')),
                ('absences', models.PositiveSmallIntegerField(default=0, help_text='Number of absences (fusenpai/kyujo)')),
                ('banzuke', models.ForeignKey(help_text='Tournament this entry belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='game.banzuke')),
                ('rank', models.ForeignKey(help_text='Rank held during this tournament', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_entries', to='game.rank')),
                ('rikishi', models.ForeignKey(help_text='Wrestler', on_delete=django.db.models.deletion.PROTECT, related_name='banzuke_entries', to='game.rikishi')),
            ],
            options={
                'verbose_name': 'Banzuke Entry',
                'verbose_name_plural': 'Banzuke Entries',
                'ordering': ['banzuke', 'rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='banzuke',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_banzuke_season'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.UniqueConstraint(fields=('banzuke', 'rikishi'), name='unique_rikishi_per_banzuke', violation_error_message='Rikishi can only appear once in a Banzuke.'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.UniqueConstraint(fields=('banzuke', 'rank'), name='unique_rank_per_banzuke', violation_error_message='Rank can only be held by one Rikishi per Banzuke.'),
        ),
    ]
