# Generated by Django 5.2.10 on 2026-01-26 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_populate_divisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heya',
            name='is_player_controlled',
        ),
    ]
