# Generated by Django 5.2.10 on 2026-01-15 00:31

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_banzuke_banzukeentry_banzuke_unique_banzuke_season_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banzuke',
            constraint=models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='banzuke_valid_month', violation_error_message='Month must be between 1 and 12.'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.CheckConstraint(condition=models.Q(('wins__lte', 15), ('losses__lte', 15), ('absences__lte', 15)), name='banzukeentry_valid_match_counts', violation_error_message='Wins, losses, and absences cannot exceed 15.'),
        ),
        migrations.AddConstraint(
            model_name='banzukeentry',
            constraint=models.CheckConstraint(condition=models.Q(('wins__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.Value(15), '-', models.F('losses')), '-', models.F('absences')))), name='banzukeentry_total_matches_max_15', violation_error_message='Total matches cannot exceed 15.'),
        ),
    ]
