# Generated by Django 5.2.10 on 2026-01-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_heya_is_player_controlled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat', models.CharField(choices=[('strength', 'Strength'), ('technique', 'Technique'), ('balance', 'Balance'), ('endurance', 'Endurance'), ('mental', 'Mental')], help_text='The stat that was trained', max_length=10)),
                ('xp_cost', models.PositiveIntegerField(help_text='XP spent on this training session')),
                ('stat_before', models.PositiveIntegerField(help_text='Stat value before training')),
                ('stat_after', models.PositiveIntegerField(help_text='Stat value after training')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the training occurred')),
                ('rikishi', models.ForeignKey(help_text='The wrestler who trained', on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to='game.rikishi')),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rikishi', '-created_at'], name='training_rikishi_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('xp_cost__gt', 0)), name='training_xp_cost_positive', violation_error_message='XP cost must be positive.'), models.CheckConstraint(condition=models.Q(('stat_after__gt', models.F('stat_before'))), name='training_stat_increased', violation_error_message='Stat after must be greater than stat before.')],
            },
        ),
    ]
