# Generated by Django 5.2.5 on 2025-10-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_shusshin_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shikona',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='game.shikona'),
        ),
    ]
