# Generated by Django 5.2.10 on 2026-01-26 18:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_add_banzuke_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(help_text='Tournament day (1-15)')),
                ('winner', models.CharField(choices=[('east', 'East'), ('west', 'West')], help_text='Winner position (east or west)', max_length=4)),
                ('kimarite', models.CharField(help_text='Winning technique used', max_length=32)),
                ('east_xp_gain', models.PositiveIntegerField(help_text='XP gained by east rikishi')),
                ('west_xp_gain', models.PositiveIntegerField(help_text='XP gained by west rikishi')),
                ('excitement_level', models.DecimalField(decimal_places=1, help_text='Excitement level from 1.0 to 10.0', max_digits=3)),
                ('commentary', models.TextField(help_text='Match commentary/description')),
                ('banzuke', models.ForeignKey(help_text='Tournament this bout belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='bouts', to='game.banzuke')),
                ('east_rikishi', models.ForeignKey(help_text='Wrestler on the east side', on_delete=django.db.models.deletion.PROTECT, related_name='bouts_as_east', to='game.rikishi')),
                ('west_rikishi', models.ForeignKey(help_text='Wrestler on the west side', on_delete=django.db.models.deletion.PROTECT, related_name='bouts_as_west', to='game.rikishi')),
            ],
            options={
                'verbose_name': 'Bout',
                'verbose_name_plural': 'Bouts',
                'ordering': ['banzuke', 'day'],
                'indexes': [models.Index(fields=['banzuke', 'day'], name='bout_banzuke_day_idx')],
                'constraints': [models.UniqueConstraint(fields=('banzuke', 'east_rikishi', 'west_rikishi'), name='unique_bout_per_tournament', violation_error_message='These wrestlers have already fought in this tournament.'), models.CheckConstraint(condition=models.Q(('day__gte', 1), ('day__lte', 15)), name='bout_valid_day', violation_error_message='Day must be between 1 and 15.'), models.CheckConstraint(condition=models.Q(('excitement_level__gte', Decimal('1.0')), ('excitement_level__lte', Decimal('10.0'))), name='bout_valid_excitement_level', violation_error_message='Excitement level must be between 1.0 and 10.0.')],
            },
        ),
    ]
