# Generated by Django 5.2.5 on 2025-10-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_shikona_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shikona',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent shikona representing name lineage or evolution. In sumo tradition, wrestlers may adopt names honoring previous legendary wrestlers, or when a wrestler retires and becomes an oyakata (stable master), their former ring name may be inherited by a successor. This field tracks such historical relationships.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='game.shikona'),
        ),
    ]
