# Generated by Django 5.2.10 on 2026-01-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_bout'),
        ('game', '0006_training_session'),
    ]

    operations = [
    ]
