# Generated by Django 5.2.5 on 2025-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_shikona_parent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shikona',
            constraint=models.CheckConstraint(condition=models.Q(('parent__isnull', True), models.Q(('parent', models.F('id')), _negated=True), _connector='OR'), name='shikona_parent_not_self', violation_error_message='A shikona cannot be its own parent.'),
        ),
    ]
