# Generated by Django 5.2.10 on 2026-03-24 16:25

import django.db.models.deletion
from django.apps.registry import Apps
from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def set_existing_shikona_unavailable(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Mark all pre-existing shikona as unavailable (already assigned)."""
    Shikona = apps.get_model("game", "Shikona")
    Shikona.objects.all().update(is_available=False)


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_bout_and_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shikona',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this shikona is available in the pool.'),
        ),
        migrations.AddField(
            model_name='shikona',
            name='reserved_at',
            field=models.DateTimeField(blank=True, help_text='When this shikona was reserved for selection.', null=True),
        ),
        migrations.AddField(
            model_name='shikona',
            name='reserved_by',
            field=models.ForeignKey(blank=True, help_text='User who reserved this shikona.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_shikona', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            set_existing_shikona_unavailable,
            migrations.RunPython.noop,
        ),
    ]
