# Generated by Django 5.2.10 on 2026-03-25 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_merge_bout_and_training'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPoolShikona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed')], default='available', help_text='Current availability status', max_length=10)),
                ('reserved_at', models.DateTimeField(blank=True, help_text='When this entry was reserved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserved_by', models.ForeignKey(blank=True, help_text='User who has reserved this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_draft_shikona', to=settings.AUTH_USER_MODEL)),
                ('shikona', models.OneToOneField(help_text='The pre-generated ring name', on_delete=django.db.models.deletion.PROTECT, related_name='draft_pool_entry', to='game.shikona')),
            ],
            options={
                'verbose_name': 'Draft Pool Shikona',
                'verbose_name_plural': 'Draft Pool Shikona',
            },
        ),
    ]
