# Generated by Django 5.2.5 on 2025-10-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_shikona_shikona_parent_not_self'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Game Date',
                'verbose_name_plural': 'Game Dates',
                'ordering': ['-year', '-month', '-day'],
                'constraints': [models.CheckConstraint(condition=models.Q(('month__gte', 1), ('month__lte', 12)), name='gamedate_month_valid_range', violation_error_message='Month must be between 1 and 12.'), models.CheckConstraint(condition=models.Q(('day__gte', 1), ('day__lte', 24)), name='gamedate_day_valid_range', violation_error_message='Day must be between 1 and 24.'), models.UniqueConstraint(fields=('year', 'month', 'day'), name='unique_game_date', violation_error_message='This game date already exists.')],
            },
        ),
    ]
