# Generated by Django 5.2.10 on 2026-03-25 00:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_draftpoolwrestler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftpoolshikona',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed')], db_index=True, default='available', help_text='Current availability status', max_length=10),
        ),
        migrations.AlterField(
            model_name='draftpoolwrestler',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('consumed', 'Consumed')], db_index=True, default='available', help_text='Current availability status', max_length=10),
        ),
        migrations.AlterConstraint(
            model_name='draftpoolwrestler',
            name='draft_pool_wrestler_jp_prefecture',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('country_code', 'JP'), models.Q(('jp_prefecture', ''), _negated=True)), models.Q(models.Q(('country_code', 'JP'), _negated=True), ('jp_prefecture', '')), _connector='OR'), name='draft_pool_wrestler_jp_prefecture', violation_error_message='Japanese wrestlers require a prefecture; non-Japanese wrestlers must not have one.'),
        ),
    ]
