# Generated by Django 5.2.5 on 2025-10-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gamedate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gamedate',
            index=models.Index(fields=['-year', '-month', '-day'], name='gamedate_current_date_idx'),
        ),
    ]
