# Generated by Django 5.2.5 on 2025-10-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_division_rank_rikishi_rikishistats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rikishi',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='rikishi',
            name='intai',
        ),
        migrations.RemoveField(
            model_name='rikishi',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='rikishi',
            name='shusshin',
        ),
        migrations.RemoveField(
            model_name='rikishistats',
            name='rikishi',
        ),
        migrations.AlterField(
            model_name='division',
            name='level',
            field=models.PositiveSmallIntegerField(help_text='Division level (1=Makuuchi/highest, 8=Banzuke-gai/lowest)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('M', 'Makuuchi'), ('J', 'Juryo'), ('Ms', 'Makushita'), ('Sd', 'Sandanme'), ('Jd', 'Jonidan'), ('Jk', 'Jonokuchi'), ('Mz', 'Mae-zumo'), ('Bg', 'Banzuke-gai')], help_text='Division short code (e.g., M=Makuuchi, J=Juryo)', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.CheckConstraint(condition=models.Q(('level__gte', 1), ('level__lte', 8)), name='division_level_valid_range', violation_error_message='Division level must be between 1 and 8.'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_division_name'),
        ),
        migrations.DeleteModel(
            name='Rikishi',
        ),
        migrations.DeleteModel(
            name='RikishiStats',
        ),
    ]
