# Generated by Django 5.2.5 on 2025-10-22 07:29

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

from game.enums import Division as DivisionEnum


def populate_divisions(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Populate the Division table with all 8 sumo divisions."""
    Division = apps.get_model("game", "Division")

    divisions_data = [
        (1, DivisionEnum.MAKUUCHI.value),
        (2, DivisionEnum.JURYO.value),
        (3, DivisionEnum.MAKUSHITA.value),
        (4, DivisionEnum.SANDANME.value),
        (5, DivisionEnum.JONIDAN.value),
        (6, DivisionEnum.JONOKUCHI.value),
        (7, DivisionEnum.MAE_ZUMO.value),
        (8, DivisionEnum.BANZUKE_GAI.value),
    ]

    Division.objects.bulk_create(
        [
            Division(level=level, name=name)
            for level, name in divisions_data
        ]
    )


def unpopulate_divisions(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Remove all divisions from the Division table."""
    Division = apps.get_model("game", "Division")
    Division.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_update_division_model_with_enum'),
    ]

    operations = [
        migrations.RunPython(populate_divisions, unpopulate_divisions),
    ]
