# Generated by Django 5.2.5 on 2025-10-28 14:33

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_rikishi_rikishistats_rikishi_rikishi_shikona_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rikishistats',
            constraint=models.CheckConstraint(condition=models.Q(('strength__gte', 1)), name='rikishistats_strength_min', violation_error_message='Strength must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishistats',
            constraint=models.CheckConstraint(condition=models.Q(('technique__gte', 1)), name='rikishistats_technique_min', violation_error_message='Technique must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishistats',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 1)), name='rikishistats_balance_min', violation_error_message='Balance must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishistats',
            constraint=models.CheckConstraint(condition=models.Q(('endurance__gte', 1)), name='rikishistats_endurance_min', violation_error_message='Endurance must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishistats',
            constraint=models.CheckConstraint(condition=models.Q(('mental__gte', 1)), name='rikishistats_mental_min', violation_error_message='Mental must be at least 1.'),
        ),
        migrations.AddConstraint(
            model_name='rikishistats',
            constraint=models.CheckConstraint(condition=models.Q(('potential__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('strength'), '+', models.F('technique')), '+', models.F('balance')), '+', models.F('endurance')), '+', models.F('mental')))), name='rikishistats_current_within_potential', violation_error_message='Total stats cannot exceed potential.'),
        ),
    ]
